services:

  postgres:
    container_name: podfish_postgres
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    image: postgres:latest
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  api:
    build:
      context: api
      target: ${ENVIRONMENT}
    container_name: podfish_api
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    restart: on-failure
    stop_grace_period: 3s
    volumes:
      - ./api:/podfish-src
      - ./rss_data:/podfish-data

  ui:
    build:
      context: ui
      target: ${ENVIRONMENT}
    container_name: podfish_ui
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:${UI_PORT}:${UI_PORT}
    restart: on-failure
    stop_grace_period: 3s
    volumes:
      - ./ui:/podfish-src
      - /podfish-src/node_modules

volumes:
  pg_data:
